"use client";
import Link from "next/link";
import { signIn } from "next-auth/react";
import { useRouter } from "next/navigation";
import { useState } from "react";

export function AuthForm({ mode }: { mode: "login" | "register" }) {
  const router = useRouter(); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const register = mode === "register";
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); const form = new FormData(event.currentTarget);
    if (register) { const response = await fetch("/api/auth/register", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) }); const body = await response.json(); if (!response.ok) { setError(body.error); setLoading(false); return; } }
    const result = await signIn("credentials", { email: form.get("email"), password: form.get("password"), redirect: false }); if (result?.error) { setError("Incorrect email or password."); setLoading(false); return; } router.replace("/dashboard"); router.refresh(); }
  return <main className="grid min-h-screen place-items-center bg-slate-50 px-5 py-10"><div className="w-full max-w-md"><Link href="/" className="mb-10 flex justify-center font-bold text-xl">payproof</Link><section className="rounded-2xl border bg-white p-8 shadow-sm"><h1 className="text-3xl font-bold">{register ? "Set up your workspace" : "Log in to PayProof"}</h1><form onSubmit={submit} className="mt-7 space-y-4">{register && <><input name="ownerName" required placeholder="Your name" className="w-full rounded-lg border p-3"/><input name="businessName" required placeholder="Business name" className="w-full rounded-lg border p-3"/><input name="phone" required placeholder="Phone number" className="w-full rounded-lg border p-3"/><select name="businessCategory" className="w-full rounded-lg border p-3"><option value="RETAIL">Retail</option><option value="ONLINE_SELLER">Online seller</option><option value="SERVICES">Services</option><option value="OTHER">Other</option></select></>}<input name="email" required type="email" autoComplete="email" placeholder="Email address" className="w-full rounded-lg border p-3"/><input name="password" required type="password" minLength={8} autoComplete={register ? "new-password" : "current-password"} placeholder="Password" className="w-full rounded-lg border p-3"/>{error && <p role="alert" className="text-sm text-red-700">{error}</p>}<button disabled={loading} className="w-full rounded-lg bg-blue-600 p-3 font-semibold text-white">{loading ? "Please wait…" : register ? "Create workspace" : "Log in"}</button></form><p className="mt-5 text-sm">{register ? "Already registered?" : "New to PayProof?"} <Link className="font-bold text-blue-600" href={register ? "/login" : "/register"}>{register ? "Log in" : "Create an account"}</Link></p></section></div></main>;
}
